### PR TITLE
fix recomendation html layouts, remove RFC6350.adoc

### PR DESCRIPTION
**Pull request by w00lf**
#43

### CODE REVIEW

**Comment by w00lf** [comment]
#45

**Comment by ronaldtse** [comment]
Thanks @w00lf , could we fix the Hound issues too?

**Comment by w00lf** [comment]
@ronaldtse how can i run hound locally? When i try to run `rubocop` it crushes with load error.

**Comment by w00lf** [comment]
@ronaldtse i tried to fix hound warnings as much as i could but there are warnings that can be safely addressed here - class names and nesting, i will need to inspect included gems in order to not break anything, should i sepnd more time on this or is it fine now?

**Comment by ronaldtse** [comment]
@w00lf then let's skip those for now. Refactoring and cleaning up is hard to complete in a day!

Also, could you help add an example document here so that in RSpec we can test generation to make sure the existing document passes? Thanks!

**Comment by ronaldtse** [comment]
@opoudjis can you help review and merge this? Thanks.

**Comment by opoudjis** [comment]
Is hound and rubocop doing the same thing? @andrew2net reports they still are not.

**Comment by opoudjis** [comment]
> Also, could you help add an example document here so that in RSpec we can test generation to make sure the existing document passes? Thanks!

Do NO SUCH THING. 

Ronald. We made a point of removing documents from the gems last year, because of how long they took to run. There will be no making up testing regimes on the fly. The mn-samples-* repositories are dedicated to testing document generation, and that shall remain the case.

**Comment by ronaldtse** [comment]
So you're saying that we will run flavor specs against mn-samples-{flavor} prior to release, right? Frankly they are run pretty quick now, so there shouldn't be excuses to not run them.

To do this we will need to add a spec for each flavor to test against samples (and templates).

**Comment by opoudjis** [comment]
Frankly they are nowhere near quick enough. Releases still take me 2-3 hours, and will continue to because of the heavy interdependencies. Do not make my life even more unpleasant than it already is.

**Pull request merged**
